#!/usr/bin/env bash
# Script to install Nginx and configure it to return "Hello World!" 

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -C 'echo "Hello world!" > /var/www/html/index.html'
service nginx restart
