#!/usr/bin/env bash
# Script to install Nginx and configure it to return "Hello World!" 

apt-get update -y
apt-get install -y nginx
sudo ufw allow 'NGIX HTTP'

sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx restart
