#!/usr/bin/env bash
# Script to configure Nginx with a custom 404 page

echo "Ceci n'est pas une page" > /var/www/html/404.html

cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    error_page 404 /404.html;
    location /404.html {
        root /var/www/html;
        internal;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF

service nginx restart

