#!/usr/bin/env bash
# Install the ufw firewall and setup rules on web-01

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
echo "y" | sudo ufw enable
