#!/usr/bin/env bash
# make a shorter script
apt-get update
apt-get install -y apache2
service apache2 start
if pgrep apache2 > /dev/null
then
    echo "apache2 is running"
else
    echo "apache2 is not running"
fi
